language: python
python:
- '3.6'
install:
- pip3 install flake8==3.8.3
- "./scripts/install-latest-px.sh"
script:
- "./scripts/lint.sh"
- "./scripts/build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_3fab9f21603e_key -iv $encrypted_3fab9f21603e_iv
  -in gcs-sa.json.enc -out gcs-sa.json -d
